### ISSUE TITLE
Segmentation fault (core dumped) & Could not process Matrix Market banner.

### ISSUE THREAD

**Issue by Pogozhelskaya** [gunrock/graphblast#7]
Is it okay that all examples fail on graphs  small/test_spgemm.mtx and small/test_sgm.mtx?

**Comment by ctcyang** [comment]
It's fine for it to fail on small/test_spgemm.mtx, because it's not a correctly formatted .mtx file.

For small/test_sgm.mtx which is a correctly formatted .mtx file, the interaction between GRB_UTIL_REMOVE_SELFLOOP=1, which removes all edges e(i,j) i=j and the .mtx file only having such edges results in reading in 3 arrays row_indices, col_indices and values with size 0. This is then handled poorly by the Matrix::build method. Will be fixed.

**Comment by ctcyang** [comment]
This issue was fixed with 1a05255.
